### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by jojobyte** [sindresorhus/conf#23]
This just took forever to track down. Been trying to get some Karma tests working in an Electron project and have been getting these errors.

```bash
# The initial error

WARNING in ./~/any-promise/register.js
24:14-37 Critical dependency: the request of a dependency is an expression

WARNING in ./~/conf/index.js
21:27-43 Critical dependency: the request of a dependency is an expression
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  567 kB       0
    chunk    {0} index.html 541 kB [entry]
        [0] ./~/lodash/lodash.js 540 kB {0}
        [1] ./~/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.11 kB {0}
        [2] (webpack)/buildin/module.js 517 bytes {0}
Electron 1.7.4 (Node 7.9.0) ERROR
# Initial Error
  Uncaught TypeError: Cannot read property 'filename' of undefined
  at webpack:///~/conf/index.js:13:0 <- index.js:27358
```

```bash
# ran `npm i -S conf` and it switched to this

WARNING in ./~/any-promise/register.js
24:14-37 Critical dependency: the request of a dependency is an expression

WARNING in ./~/conf/index.js
21:27-43 Critical dependency: the request of a dependency is an expression
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  567 kB       0
    chunk    {0} index.html 541 kB [entry]
        [0] ./~/lodash/lodash.js 540 kB {0}
        [1] ./~/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.11 kB {0}
        [2] (webpack)/buildin/module.js 517 bytes {0}
Electron 1.7.4 (Node 7.9.0) ERROR
# this is what changed 
  Uncaught Error: Cannot find module "."
  at webpack:///~/conf/index.js:21:0 <- index.js:27366
```

It is related to `import Store from 'electron-store';`

After commenting out that import and replacing it with the below code, the Karma spec functions as expected:

```js
class Store {
  constructor (options = {}) {
    const opt = {
    };

    this.options = Object.assign({}, opt, options);
    this.data = {};
  }

  set (key, value) {
    this.data[key] = value;
  }

  has (key) {
    return !!this.data[key];
  }
}
```

Any help resolving this would be much appreciated.

Thanks!

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/electron-store/issues/9
